/*******************************************************
* Fixed.frag Fixed Function Equivalent Fragment Shader *
*        Automatically Generated by GLSL ShaderGen     *
*          https://github.com/mojocorp/ShaderGen       *
*******************************************************/
uniform sampler2D texUnit0;

in vec4 Color;
in vec2 TexCoord;

void main(void)
{
    vec4 color;

    //color = gl_Color;
    color = Color;

    //color *= texture2D(texUnit0, gl_TexCoord[0].xy);
    color *= texture2D(texUnit0, TexCoord.xy);

    gl_FragColor = color;
}
